### ISSUE TITLE
Milestone 1 tasks

### ISSUE THREAD

**Issue by Arushi282** [UBC-MDS/dsci525-group20#1]
Tasks:

- [x] Team-work contract (Arushi)
- [x] Creating repository and project structure (Thomas)
- [x] Readme (Thomas)
- [x] Downloading the data (Thomas)
- [x] Combining data CSVs (Thomas)
- [x] Load the combined CSV to memory (Thomas)
- [x] Perform a simple EDA python (Arushi)
- [x] Transfer dataframe from python to R (Simon, Dongxiao)
- [x] Perform a simple EDA in R (Simon)
